version: '2.2'
services:
  # This is the official BF2 1.5 dedicated server.
  # A default ESAI strategy and custom ESAI strategies for maps are configured in entrypoint
  bf2:
    image: startersclan/docker-bf2:v1.5.3153.0
    volumes:
      - ./config/bf2/mods/bf2/ai/aidefault-custom.ai:/server/bf2/mods/bf2/ai/aidefault.ai:ro # Customize bots
      - ./config/strategies.txt:/strategies.txt # Custom ESAI strategies for levels
      - ./config/bf2/mods/bf2/settings/serversettings-custom.con:/server/bf2/mods/bf2/settings/serversettings.con:ro # Server config
      - ./config/bf2/mods/bf2/settings/maplist-custom-coop.con:/server/bf2/mods/bf2/settings/maplist.con:ro # Maplist
    ports:
      - 16567:16567/udp
      - 29900:29900/udp
    networks:
      - default
    healthcheck:
      test: /healthcheck localhost 29900
    tty: true
    stdin_open: true
    entrypoint:
      - /bin/bash
    command:
      - -c
      - |
          set -eu
          esai-helper --mod bf2 apply default-strategy mediumfca
          esai-helper --mod bf2 apply -f /strategies.txt
          exec ./start.sh

networks:
  default:
