version: '2.2'
services:
  # This is the official BF2 1.5 dedicated server. It uses BF2Hub as the master server, but your private ASP web server (i.e. stats server) by DNS spoofing.
  # For a full bf2stats 3 stack example, see https://github.com/startersclan/ASP
  bf2:
    image: startersclan/docker-bf2:v1.5.3153.0-bf2stats-3.1.0
    volumes:
      - ./config/bf2/mods/bf2/ai/aidefault-custom.ai:/server/bf2/mods/bf2/ai/aidefault.ai:ro # Customize bots
      # - ./config/bf2/mods/bf2/ai/aidefaultstrategies-custom-esai.ai:/server/bf2/mods/bf2/ai/aidefaultstrategies.ai:ro # Enable ESAI with a default strategy for all maps. The same can be achieved using: esai-helper apply default-strategy mediumfca
      # - ./config/bf2/mods/bf2/ai/aidefaultstrategiesadd-custom-esai.ai:/server/bf2/mods/bf2/ai/aidefaultstrategiesadd.ai:ro # Enable ESAI with a default strategy for all maps. The same can be achieved using: esai-helper apply default-strategy mediumfca
      - ./config/bf2/mods/bf2/settings/serversettings-custom.con:/server/bf2/mods/bf2/settings/serversettings.con:ro # Server config
      - ./config/bf2/mods/bf2/settings/maplist-custom-coop.con:/server/bf2/mods/bf2/settings/maplist.con:ro # Maplist
      - ./config/bf2/python/bf2/BF2StatisticsConfig-custom.py:/server/bf2/python/bf2/BF2StatisticsConfig.py:ro # bf2stats python config
    ports:
      - 16567:16567/udp
      - 29900:29900/udp
    networks:
      - default
    extra_hosts:
      - battlefield2.available.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - battlefield2.master.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - battlefield2.ms14.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - master.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - motd.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - gpsp.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - gpcm.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - bf2web.gamespy.com:192.168.1.100 # Your ASP web server IP
      - gamestats.gamespy.com:192.168.1.100 # Your ASP web server IP
      - eapusher.dice.se:192.168.1.100 # Your ASP web server IP
    healthcheck:
      test: /healthcheck localhost 29900
    tty: true
    stdin_open: true

networks:
  default:
