version: '2.2'
services:
  # This is the official BF2 1.5 dedicated server.
  bf2:
    image: startersclan/docker-bf2:v1.5.3153.0
    volumes:
      - ./config/bf2/mods/bf2/ai/aidefault-custom.ai:/server/bf2/mods/bf2/ai/aidefault.ai:ro # Customize bots
      - ./config/bf2/mods/bf2/settings/serversettings-custom.con:/server/bf2/mods/bf2/settings/serversettings.con:ro # Server config
      - ./config/bf2/mods/bf2/settings/maplist-custom-coop.con:/server/bf2/mods/bf2/settings/maplist.con:ro # Maplist
    ports:
      - 16567:16567/udp
      - 29900:29900/udp
    networks:
      - default
    extra_hosts:
      - battlefield2.available.gamespy.com:192.168.1.100 # PRMasterServer IP
      - battlefield2.master.gamespy.com:192.168.1.100 # PRMasterServer IP
      - battlefield2.ms14.gamespy.com:192.168.1.100 # PRMasterServer IP
      - master.gamespy.com:192.168.1.100 # PRMasterServer IP
      - motd.gamespy.com:192.168.1.100 # PRMasterServer IP
      - gpsp.gamespy.com:192.168.1.100 # PRMasterServer IP
      - gpcm.gamespy.com:192.168.1.100 # PRMasterServer IP
      - gamespy.com:192.168.1.100 # PRMasterServer IP
    healthcheck:
      test: /healthcheck localhost 29900
    tty: true
    stdin_open: true

networks:
  default:
