version: '2.2'
services:
  # This is the official BF2 1.5 dedicated server running the Forgotten Hope 2 mod.
  bf2:
    image: startersclan/docker-bf2:v1.5.3153.0-fh2-4.6.304
    volumes:
      - ./config/bf2/mods/fh2/ai/aidefault-custom.ai:/server/bf2/mods/fh2/ai/aidefault.ai:ro # Customize bots
      - ./config/bf2/mods/fh2/settings/serversettings-custom.con:/server/bf2/mods/fh2/settings/serversettings.con:ro # Server config
      - ./config/bf2/mods/fh2/settings/maplist-custom-coop.con:/server/bf2/mods/fh2/settings/maplist.con:ro # Maplist
    ports:
      - 16567:16567/udp
      - 29900:29900/udp
    healthcheck:
      test: /healthcheck localhost 29900
    networks:
      - default
    tty: true
    stdin_open: true

networks:
  default:
