version: '2.2'
services:
  # This is the official BF2 1.5 dedicated server running the BF2All64 mod.
  # A default ESAI strategy and optimized ESAI strategies for maps are configured in entrypoint
  bf2:
    image: startersclan/docker-bf2:v1.5.3153.0-bf2all64
    volumes:
      - ./config/bf2/mods/bf2all64/ai/aidefault-custom.ai:/server/bf2/mods/bf2all64/ai/aidefault.ai:ro # Customize bots
      - ./config/bf2/mods/bf2all64/ai/aibehaviours-fixlookatwrapper.ai:/server/bf2/mods/bf2all64/ai/aibehaviours.ai:ro # LoopAtWrapper fix
      # - ./config/bf2/mods/bf2all64/ai/aidefaultstrategies-custom-esai.ai:/server/bf2/mods/bf2all64/ai/aidefaultstrategies.ai:ro # Enable ESAI with a default strategy for all maps. The same can be achieved using: esai-helper --mod bf2all64 apply default-strategy mediumfca
      # - ./config/bf2/mods/bf2all64/ai/aidefaultstrategiesadd-custom-esai.ai:/server/bf2/mods/bf2all64/ai/aidefaultstrategiesadd.ai:ro # Enable ESAI with a default strategy for all maps. The same can be achieved using: esai-helper --mod bf2all64 apply default-strategy mediumfca
      - ./config/bf2/mods/bf2all64/settings/serversettings-custom.con:/server/bf2/mods/bf2all64/settings/serversettings.con:ro # Server config
      - ./config/bf2/mods/bf2all64/settings/maplist-custom-coop.con:/server/bf2/mods/bf2all64/settings/maplist.con:ro # Maplist
      - ./config/bf2/python/bf2/BF2StatisticsConfig-custom.py:/server/bf2/python/bf2/BF2StatisticsConfig.py:ro # bf2stats python config
    ports:
      - 16567:16567/udp
      - 29900:29900/udp
    networks:
      - default
    healthcheck:
      test: /healthcheck localhost 29900
    tty: true
    stdin_open: true
    entrypoint:
      - /bin/bash
    command:
      - -c
      - |
          set -eu
          esai-helper --mod bf2all64 apply default-strategy mediumfca
          esai-helper --mod bf2all64 apply -f /esai-optimized-strategies-bf2all64.txt
          exec ./start.sh

networks:
  default:
