version: '2.2'
services:
  # This is the official BF2 1.5 dedicated server with the BF2All64 mod.
  # A default ESAI strategy is configured in entrypoint
  # In addition, optimized ESAI strategies are configured in entrypoint
  bf2:
    image: startersclan/docker-bf2:v1.5.3153.0-bf2all64
    volumes:
      - ./config/bf2/mods/bf2all64/ai/aidefault-custom.ai:/server/bf2/mods/bf2all64/ai/aidefault.ai:ro # Customize bots
      - ./config/bf2/mods/bf2all64/ai/aibehaviours-fixlookatwrapper.ai:/server/bf2/mods/bf2all64/ai/aibehaviours.ai:ro # LoopAtWrapper fix
      # - ./config/bf2/mods/bf2all64/ai/aidefaultstrategies-custom-esai.ai:/server/bf2/mods/bf2all64/ai/aidefaultstrategies.ai:ro # Enable ESAI with a default strategy for all maps. The same can be achieved using: esai-helper --mod bf2all64 apply default-strategy mediumfca
      # - ./config/bf2/mods/bf2all64/ai/aidefaultstrategiesadd-custom-esai.ai:/server/bf2/mods/bf2all64/ai/aidefaultstrategiesadd.ai:ro # Enable ESAI with a default strategy for all maps. The same can be achieved using: esai-helper --mod bf2all64 apply default-strategy mediumfca
      - ./config/bf2/mods/bf2all64/settings/serversettings-custom.con:/server/bf2/mods/bf2all64/settings/serversettings.con:ro # Server config
      - ./config/bf2/mods/bf2all64/settings/maplist-custom-coop.con:/server/bf2/mods/bf2all64/settings/maplist.con:ro # Maplist
      - ./config/bf2/python/bf2/BF2StatisticsConfig-custom.py:/server/bf2/python/bf2/BF2StatisticsConfig.py:ro # bf2stats python config
    ports:
      - 16567:16567/udp
      - 29900:29900/udp
    extra_hosts:
      - battlefield2.available.gamespy.com:192.168.1.100 # Your master server IP
      - battlefield2.master.gamespy.com:92.51.181.102 # Your master server IP
      - battlefield2.ms14.gamespy.com:92.51.181.102 # Your master server IP
      - master.gamespy.com:92.51.181.102 # Your master server IP
      - motd.gamespy.com:92.51.181.102 # Your master server IP
      - gpsp.gamespy.com:92.51.181.102 # Your master server IP
      - gpcm.gamespy.com:92.51.181.102 # Your master server IP
      - gamespy.com:92.51.181.102 # Your master server IP
      - bf2web.gamespy.com:92.51.180.45 # Your ASP web server IP
      - gamestats.gamespy.com:92.51.180.45 # Your ASP web server IP
      - eapusher.dice.se:92.51.180.45 # Your ASP web server IP
    networks:
      - default
    tty: true
    stdin_open: true
    entrypoint:
      - /bin/bash
    command:
      - -c
      - |
          set -eu
          esai-helper --mod bf2all64 apply default-strategy mediumfca
          esai-helper --mod bf2all64 apply -f /esai-optimized-strategies-bf2all64.txt
          exec ./start.sh"

networks:
  default:
