version: '2.2'
services:
  # This is the official BF2 1.5 dedicated server. It uses BF2Hub as the master server and the ASP web server (i.e. stats server) by DNS spoofing.
  # Server will be unranked because it is not an official BF2Hub ranked server
  bf2:
    image: startersclan/docker-bf2:v1.5.3153.0
    volumes:
      - ./config/bf2/mods/bf2/ai/aidefault-custom.ai:/server/bf2/mods/bf2/ai/aidefault.ai:ro # Customize bots
      # - ./config/bf2/mods/bf2/ai/aidefaultstrategies-custom-esai.ai:/server/bf2/mods/bf2/ai/aidefaultstrategies.ai:ro # Enable ESAI with a default strategy for all maps. The same can be achieved using: esai-helper apply default-strategy mediumfca
      # - ./config/bf2/mods/bf2/ai/aidefaultstrategiesadd-custom-esai.ai:/server/bf2/mods/bf2/ai/aidefaultstrategiesadd.ai:ro # Enable ESAI with a default strategy for all maps. The same can be achieved using: esai-helper apply default-strategy mediumfca
      - ./config/bf2/mods/bf2/settings/serversettings-custom.con:/server/bf2/mods/bf2/settings/serversettings.con:ro # Server config
      - ./config/bf2/mods/bf2/settings/maplist-custom-coop.con:/server/bf2/mods/bf2/settings/maplist.con:ro # Maplist
    ports:
      - 16567:16567/udp
      - 29900:29900/udp
    networks:
      - default
    extra_hosts:
      - battlefield2.available.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - battlefield2.master.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - battlefield2.ms14.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - master.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - motd.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - gpsp.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - gpcm.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - bf2web.gamespy.com:92.51.180.45 # bf2hub.com ASP web server IP
      - gamestats.gamespy.com:92.51.180.45 # bf2hub.com ASP web server IP
      - eapusher.dice.se:92.51.180.45 # bf2hub.com ASP web server IP
    healthcheck:
      test: /healthcheck localhost 29900
    tty: true
    stdin_open: true

networks:
  default:
